
tools:
        php_code_sniffer: true
        php_cpd: true
        # php_cs_fixer: true
        php_hhvm: true
        php_loc: true
        php_mess_detector: true
        php_pdepend: true
        php_analyzer: true
        external_code_coverage:
                timeout: 600
